# Site settings
title: delameko
email: admin@delameko.io
description: >
  This ain't my beautiful house
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://delameko.io" # the base hostname & protocol for your site
twitter_username: delameko
github_username:  delameko

# Build settings
markdown: kramdown
